services:

  collectify-initdb:
    build:
      context: ./backend
      dockerfile: Dockerfile.initdb
    image: lucaplawliet/collectify-initdb:latest
    container_name: collectify-initdb
    volumes:
      - collectify-data:/app/data
    restart: "no"
    entrypoint: ["python", "init_all_tables.py"]
    env_file:
      - .env

  collectify-web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: lucaplawliet/collectify-web:latest
    container_name: collectify-app
    ports:
      - "5000:5000"
    volumes:
      - collectify-data:/app/data
    depends_on:
      collectify-initdb:
        condition: service_completed_successfully
    restart: always
    entrypoint: ["/startup.sh"]
    env_file:
      - .env

  collectify-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: lucaplawliet/collectify-frontend:latest
    container_name: collectify-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://collectify-app:5000
    depends_on:
      - collectify-web

volumes:
  collectify-data:
  collectify-frontend-data:
