services:

  collectify-initdb:
    build:
      context: ./backend
      dockerfile: Dockerfile.initdb
    image: lucaplawliet/collectify-initdb:latest
    container_name: collectify-initdb
    environment:
      - COLLECTIFY_DB_PATH=/app/data/collectibles.db
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    volumes:
      - collectify-data:/app/data
    restart: "no"
    entrypoint: ["python", "init_all_tables.py"]

  collectify-web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: lucaplawliet/collectify-web:latest
    container_name: collectify-app
    ports:
      - "5000:5000"
    volumes:
      - collectify-data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    depends_on:
      collectify-initdb:
        condition: service_completed_successfully
    restart: always
    entrypoint: ["/startup.sh"]

  collectify-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: lucaplawliet/collectify-frontend:latest
    container_name: collectify-frontend
    ports:
      - "80:80"
    environment:
      - API_URL=http://collectify-app:5000
    depends_on:
      - collectify-web

volumes:
  collectify-data:
  collectify-frontend-data:
