services:
  web:
    build: .
    image: lucaplawliet/collectify-web:latest
    container_name: collectify-app
    ports:
      - "5000:5000"
    volumes:
      # Mount the data directory for persistent database and uploads
      - collectify-data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    restart: always

volumes:
  collectify-data:
