# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy to Azure Web App - collectify

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Python for backend
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Set up Node.js for frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    # Install backend dependencies
    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install frontend dependencies and build frontend
    - name: Install frontend dependencies and build
      run: |
        cd frontend
        npm ci
        # Create a production .env file with the correct API URL
        echo "REACT_APP_API_URL=/api" > .env.production
        npm run build

    # Create deployment package
    - name: Create deployment package
      run: |
        # Prepare deployment folder
        mkdir -p deployment
        
        # Copy backend files to deployment
        cp -r backend/* deployment/
        
        # Create static directories for frontend static files
        mkdir -p deployment/static/js
        mkdir -p deployment/static/css
        mkdir -p deployment/static/media
        
        # Copy built frontend to static directories
        cp -r frontend/build/* deployment/static/
        
        # Create a startup script that configures the application
        echo '#!/bin/bash
        # Add WSGI configuration
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        export FLASK_APP=app.py
        export FLASK_ENV=production
        
        # Start Gunicorn with correct path configuration
        gunicorn --bind=0.0.0.0:$PORT --workers=4 app:app
        ' > deployment/startup.sh
        chmod +x deployment/startup.sh
        
        # Create web.config file for Azure
        echo '<?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <system.webServer>
            <handlers>
              <add name="PythonHandler" path="*" verb="*" modules="FastCgiModule" scriptProcessor="%PYTHON_PATH%|%WSGI_PATH%" resourceType="Unspecified" requireAccess="Script" />
            </handlers>
            <rewrite>
              <rules>
                <rule name="Static Files" stopProcessing="true">
                  <match url="^(static|assets|js|css|media|favicon.ico)/(.*)" ignoreCase="true" />
                  <action type="Rewrite" url="static/{R:1}/{R:2}" />
                </rule>
                <rule name="API" stopProcessing="true">
                  <match url="^api/(.*)" ignoreCase="true" />
                  <action type="Rewrite" url="app.py/api/{R:1}" />
                </rule>
                <rule name="React Routes" stopProcessing="true">
                  <match url=".*" ignoreCase="true" />
                  <conditions>
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    <add input="{REQUEST_URI}" pattern="^/api" negate="true" />
                  </conditions>
                  <action type="Rewrite" url="static/index.html" />
                </rule>
              </rules>
            </rewrite>
          </system.webServer>
        </configuration>' > deployment/web.config
        
        # Modify app.py to serve static files if needed
        if grep -q "serve_static_files" deployment/app.py; then
          echo "Static file serving already configured"
        else
          # Append static file serving configuration to app.py
          echo "
        # Configure Flask to serve static files
        @app.route('/', defaults={'path': ''})
        @app.route('/<path:path>')
        def serve_static_files(path):
            if path.startswith('api/'):
                # Let Flask handle API routes
                return abort(404)
            
            # Check if file exists in static folder
            static_path = os.path.join(app.static_folder, path)
            if os.path.exists(static_path) and os.path.isfile(static_path):
                return send_from_directory(app.static_folder, path)
            
            # Serve index.html for all other routes (SPA support)
            return send_from_directory(app.static_folder, 'index.html')
        " >> deployment/app.py
        fi
        
        # Remove unnecessary files
        find deployment -type d -name "__pycache__" -exec rm -rf {} +
        find deployment -type d -name "node_modules" -exec rm -rf {} +
        rm -f deployment/Dockerfile*
        
        # Create zip file
        cd deployment
        zip -r ../collectify-deployment.zip .

    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'collectify'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d7b87d5b242444a9bc2ab07fa9a62a6b }}
        package: './collectify-deployment.zip'
    
    # Configure app settings for the web app
    - name: Configure App Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: 'collectify'
        slot-name: 'production'
        app-settings-json: |
          [
            {
              "name": "FLASK_APP",
              "value": "app.py"
            },
            {
              "name": "FLASK_ENV",
              "value": "production"
            },
            {
              "name": "FLASK_RUN_HOST",
              "value": "0.0.0.0"
            },
            {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "true"
            },
            {
              "name": "COLLECTIFY_DB_PATH",
              "value": "data/collectibles.db"
            }
          ]

    # Initialize database after deployment
    - name: Run database initialization
      uses: azure/webapps-action@v1
      with:
        app-name: 'collectify'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d7b87d5b242444a9bc2ab07fa9a62a6b }}
        startup-command: 'python init_all_tables.py'